swagger: "2.0"

info:
  description: "Faucet API doc and explorer.\n\nSend coins from the faucet account configured in `config.yml` to the receiver account."
  version: "1.0.0"
  title: "Faucet for <%= ModulePath %>"

servers:
  - url: /

paths:
  /:
    post:
      summary: "Send tokens to receiver account"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Send coins request object\n\nAfter making a sample execution by the 'Try it out' button in the right corner"
          required: true
          schema:
            $ref: "#/definitions/SendRequest"
      responses:
        "400":
          description: "Bad request"
        "500":
          description: "Internal error"
        "200":
          description: "All coins are successfully sent\n\nAfter making a sample execution"
          schema:
            $ref: "#/definitions/SendResponse"

definitions:
  SendRequest:
    type: "object"
    required:
      - address
    properties:
      address:
        type: "string"
        default: "cosmos1uzv4v9g9xln2qx2vtqhz99yxum33calja5vruz"
      coins:
        type: "array"
        default:
          - 10token
        items:
          type: "string"

  SendResponse:
    type: "object"
    properties:
      error:
        type: "string"


externalDocs:
  description: "Find out more about Ignite CLI"
  url: "https://github.com/ignite/cli/tree/main/docs"
