image:
  file: .gitpod.Dockerfile

checkoutLocation: "starport"

workspaceLocation: "./starport/docs"

tasks:
  - name: Install Starport
    before: |
      go get golang.org/dl/go1.15
      go1.15 download

    init: |
      # Install Starport
      export BIN_PATH=$GOPATH/bin
      export VUE_APP_CUSTOM_URL=$(gp url)
      export CHISEL_ADDR=$(gp url 7575)
      mkdir -p $BIN_PATH
      (cd /workspace/starport && ./scripts/install)

    command: |
      export VUE_APP_CUSTOM_URL=$(gp url)
      export CHISEL_ADDR=$(gp url 7575)
      export RPC_ADDRESS=$(gp url 26657):443
      export API_ADDRESS=$(gp url 1317)
      cd ./docs

      clear && printf '\e[3J'
      echo -e "

      Welcome to Starport! 💫 The friendly CLI that makes building blockchains easy.

      In the sidebar you can see a list of guides that will help you get started.

      This terminal has the \033[1mstarport\033[0m binary already installed and ready to go.

      "

ports:
  - port: 1317
  - port: 26657
  - port: 8080
  - port: 7575 
  - port: 4500 

vscode:
  extensions:
    - vymarkov.nodejs-devops-extension-pack@0.0.12:lLl4kIpAV9RJvYaGPctDJA==
    - zxh404.vscode-proto3@0.5.3:RT2nlrSGFR1wH2b/dRg82A==