{
  "name": "{{ replace .Module.Pkg.Name "." "-" }}-js",
  "version": "0.1.0",
  "description": "Autogenerated vuex store for Cosmos module {{ .Module.Pkg.Name }}",
  "author": "Starport Codegen <hello@tendermint.com>",
  "homepage": "http://{{ .Module.Pkg.GoImportName }}",
  "license": "Apache-2.0",
  "licenses": [
    {
      "type": "Apache-2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  ],
  "main": "index.js",
  "publishConfig": {
    "access": "public"
  }
}