package stdlibs

import (
	"math"
	"testing"

	gno "github.com/gnolang/gno/gnovm/pkg/gnolang"
)

// realm.Sub charges gas by mirroring chain.packageAddress's calibrated
// cost (its dominant work is the same bech32 derivation), but it's a
// uverse native — chargeNativeGas can't read the calibration table for
// it, so the values are hand-copied into gnolang as OpCPUSubRealmBase/
// Slope. This guards against silent drift when the table is
// regenerated by gen_native_table.py.
func TestSubRealmGasMirrorsPackageAddress(t *testing.T) {
	t.Parallel()
	var found bool
	for _, e := range calibratedNativeGas {
		if e.Pkg == "chain" && e.Fn == "packageAddress" {
			found = true
			if e.Base != gno.OpCPUSubRealmBase {
				t.Errorf("OpCPUSubRealmBase = %d, packageAddress Base = %d — recalibration drifted; update the const",
					gno.OpCPUSubRealmBase, e.Base)
			}
			if e.Slope != gno.OpCPUSubRealmSlope {
				t.Errorf("OpCPUSubRealmSlope = %d, packageAddress Slope = %d — recalibration drifted; update the const",
					gno.OpCPUSubRealmSlope, e.Slope)
			}
		}
	}
	if !found {
		t.Fatal("chain/packageAddress row missing from calibratedNativeGas")
	}
}

// TestModExpRowCoversMeasuredCalibrationPoint guards the crypto/modexp row
// against a re-fit that drops it below the only shape this native has a real
// measurement for. The superseded row charged on len(modulus) alone and was fit
// so that len(base)==len(exp)==len(modulus)==256 cost ~6.16ms on the reference
// hardware; the current row prices bits(exp) × words(modulus)² instead, but
// whatever the model, it must not charge less than that at that shape.
//
// A floor rather than an equality: the slope is fit over the ModExpGrid benches
// with headroom, so it deliberately charges more than the old row here. Only a
// drop below is a regression.
func TestModExpRowCoversMeasuredCalibrationPoint(t *testing.T) {
	t.Parallel()

	// The superseded row evaluated at a 256-byte modulus: the measured point.
	const measuredAtAnchor = 58000 + 24647680*256/1024

	var row *nativeGasEntry
	for i := range calibratedNativeGas {
		if calibratedNativeGas[i].Pkg == "crypto/modexp" && calibratedNativeGas[i].Fn == "modExp" {
			row = &calibratedNativeGas[i]
			break
		}
	}
	if row == nil {
		t.Fatal("crypto/modexp modExp row missing from calibratedNativeGas")
	}
	// Ask the runtime for the metric rather than restating it: a hardcoded
	// formula here would keep passing after a model change while silently
	// checking a different quantity than production charges.
	got := row.Base + row.Slope*gno.ModExpWork(256, 256)/1024 + row.Slope2*256/1024

	if got < measuredAtAnchor {
		t.Errorf("charge at the symmetric 256-byte shape = %d, below the %d measured "+
			"for it (Slope=%d) — a re-fit has taken this row under its one "+
			"real calibration point", got, measuredAtAnchor, row.Slope)
	}
}

// modExpGridPoint is one recorded ModExpGrid measurement. The full run, the
// machine it was taken on and the reasoning live in
// gnovm/cmd/calibrate/ibc_native_bench_test.go; these are its medians.
type modExpGridPoint struct {
	expLen, modLen int64
	devNS          float64
}

// modExpDevToReference projects the recorded run onto the reference Xeon 8168.
// The benches were taken on an AMD Ryzen 7 7840U, which is materially faster,
// so a charge that merely covers the raw numbers undercharges every validator
// on reference hardware. Four rows in this same table calibrated on a
// reference-class Xeon put the gap at 2.19-2.33x (cometbls.verifyZKP 2.19,
// bn254.pairingCheck 2.19 and 2.33, modexp's own superseded anchor 2.32).
//
// 2.3 is the HIGH end deliberately. A larger factor projects a larger cost and
// so demands a larger slope: the safe choice is the top of the measured range,
// not the bottom. An earlier revision of this constant took the low end, which
// had it backwards.
const modExpDevToReference = 2.3

var modExpRecordedGrid = []modExpGridPoint{
	{0, 32, 520},
	{0, 256, 768},
	{0, 1024, 1716},
	{1, 256, 30436},
	{1, 1024, 240084},
	{3, 256, 98887},
	{3, 1024, 792236},
	{4, 32, 8454},
	{4, 256, 123890},
	{4, 1024, 1102211},
	{8, 32, 15168},
	{8, 256, 239457},
	{8, 1024, 2088169},
	{9, 32, 17203},
	{9, 256, 210814},
	{9, 1024, 2612594},
	{16, 256, 198277},
	{24, 256, 278681},
	{32, 32, 24218},
	{32, 256, 352113},
	{32, 1024, 4641969},
	{256, 32, 165587},
	{256, 1024, 35314846},
	{1024, 32, 724654},
	{1024, 256, 10771770},
	{1024, 1024, 131967026},
}

// TestModExpRowCoversRecordedGrid is the mechanical form of the property the
// row's comment claims: its coefficients are upper bounds over the calibration
// grid, not a central fit. Checking one anchor point (as
// TestModExpRowCoversMeasuredCalibrationPoint does) cannot see a re-fit that
// dips below cost anywhere else on the surface, and the surface is where this
// native's cost actually varies — the row this replaced passed a single-point
// check while undercharging ten of twenty-six grid points.
//
// A failure here means a re-fit, a change to modExpWork, or a change to the
// crossover constants has taken the charge under measured cost at some shape.
// That is a consensus-relevant undercharge, not a stale golden value: fix the
// row, do not relax the test.
func TestModExpRowCoversRecordedGrid(t *testing.T) {
	t.Parallel()

	row := findModExpRow(t)
	if row.SlopeKind != SizeModExpWork || row.Slope2Kind != SizeLenBytes {
		t.Fatalf("row shape changed (SlopeKind=%v Slope2Kind=%v) — this test assumes "+
			"a work slope on the exponent and a per-byte slope on the modulus",
			row.SlopeKind, row.Slope2Kind)
	}

	worst, worstAt := math.Inf(1), modExpGridPoint{}
	for _, p := range modExpRecordedGrid {
		// Ask the runtime for the metric rather than restating it, so a model
		// change cannot leave this checking a different quantity than production.
		charge := row.Base +
			row.Slope*gno.ModExpWork(p.expLen, p.modLen)/1024 +
			row.Slope2*p.modLen/1024
		want := p.devNS * modExpDevToReference
		if margin := float64(charge) / want; margin < worst {
			worst, worstAt = margin, p
		}
		if float64(charge) < want {
			t.Errorf("expLen=%d modLen=%d: charge %d < %.0f ns measured "+
				"(%.0f ns on the dev box x%.2f) — the row is not an upper bound here",
				p.expLen, p.modLen, charge, want, p.devNS, modExpDevToReference)
		}
	}
	t.Logf("thinnest margin %.2fx at expLen=%d modLen=%d",
		worst, worstAt.expLen, worstAt.modLen)
}

// TestModExpChargeMonotonic: a longer exponent must never cost less. big.Int
// switches routines at a one-word exponent and the two have different per-bit
// costs, so a metric that ignores the switch can invert — the superseded one
// charged an 8-byte exponent less than a 9-byte one while measuring more
// expensive. An inversion is directly exploitable: it lets a caller buy the
// dearer computation at the cheaper shape's price.
func TestModExpChargeMonotonic(t *testing.T) {
	t.Parallel()

	row := findModExpRow(t)
	charge := func(expLen, modLen int64) int64 {
		return row.Base +
			row.Slope*gno.ModExpWork(expLen, modLen)/1024 +
			row.Slope2*modLen/1024
	}
	for _, modLen := range []int64{1, 32, 64, 256, 512, 1024} {
		for expLen := int64(1); expLen <= 1024; expLen++ {
			if prev, got := charge(expLen-1, modLen), charge(expLen, modLen); got < prev {
				t.Fatalf("modLen=%d: charge(expLen=%d)=%d < charge(expLen=%d)=%d",
					modLen, expLen, got, expLen-1, prev)
			}
		}
	}
}

func findModExpRow(t *testing.T) *nativeGasEntry {
	t.Helper()
	for i := range calibratedNativeGas {
		if calibratedNativeGas[i].Pkg == "crypto/modexp" && calibratedNativeGas[i].Fn == "modExp" {
			return &calibratedNativeGas[i]
		}
	}
	t.Fatal("crypto/modexp modExp row missing from calibratedNativeGas")
	return nil
}

// crypto/merkle.innerHash hashes 0x01||left||right and nothing bounds either
// operand, so both must be metered per byte. It shipped as a flat charge
// calibrated on 32+32B inputs, which let 1MiB+1MiB run ~300x over its price;
// a single slope would be no better, since the payload just moves to the
// unmetered operand. Guard the shape against a recalibration or a hand edit
// dropping either slope.
func TestInnerHashGasMetersBothOperands(t *testing.T) {
	t.Parallel()
	var inner, leaf *nativeGasEntry
	for i, e := range calibratedNativeGas {
		if e.Pkg != "crypto/merkle" {
			continue
		}
		switch e.Fn {
		case "innerHash":
			inner = &calibratedNativeGas[i]
		case "leafHash":
			leaf = &calibratedNativeGas[i]
		}
	}
	if inner == nil || leaf == nil {
		t.Fatal("crypto/merkle innerHash and/or leafHash row missing from calibratedNativeGas")
	}

	if inner.SlopeKind != SizeLenBytes || inner.SlopeIdx != 0 || inner.Slope == 0 {
		t.Errorf("innerHash must meter left (param 0) per byte; got Slope=%d SlopeIdx=%d SlopeKind=%d",
			inner.Slope, inner.SlopeIdx, inner.SlopeKind)
	}
	if inner.Slope2Kind != SizeLenBytes || inner.Slope2Idx != 1 || inner.Slope2 == 0 {
		t.Errorf("innerHash must meter right (param 1) per byte; got Slope2=%d Slope2Idx=%d Slope2Kind=%d",
			inner.Slope2, inner.Slope2Idx, inner.Slope2Kind)
	}

	// Both operands feed one SHA256 over their concatenation, so each byte
	// costs what a leafHash byte costs. Charging less would undercharge the
	// same work leafHash is already calibrated for.
	if inner.Slope < leaf.Slope || inner.Slope2 < leaf.Slope {
		t.Errorf("innerHash per-operand rates (%d, %d) below leafHash's %d — both hash their input at the same rate",
			inner.Slope, inner.Slope2, leaf.Slope)
	}
}
