FROM faddat/sos-lite

# Add seeds and such after doing gaia.
# I will prototype the rest of this on gaia.
RUN echo blurt > /etc/hostname && \
		echo "docker run faddat/blurt2" >> /usr/local/bin/firstboot.sh
