// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ignite/services/plugin/grpc/v1/service.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{0}
}

type ManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           *ExecutedCommand       `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	ClientApi     uint32                 `protobuf:"varint,2,opt,name=client_api,json=clientApi,proto3" json:"client_api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetCmd() *ExecutedCommand {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *ExecuteRequest) GetClientApi() uint32 {
	if x != nil {
		return x.ClientApi
	}
	return 0
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{3}
}

type ExecuteHookPreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          *ExecutedHook          `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	ClientApi     uint32                 `protobuf:"varint,2,opt,name=client_api,json=clientApi,proto3" json:"client_api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteHookPreRequest) Reset() {
	*x = ExecuteHookPreRequest{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteHookPreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteHookPreRequest) ProtoMessage() {}

func (x *ExecuteHookPreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteHookPreRequest.ProtoReflect.Descriptor instead.
func (*ExecuteHookPreRequest) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteHookPreRequest) GetHook() *ExecutedHook {
	if x != nil {
		return x.Hook
	}
	return nil
}

func (x *ExecuteHookPreRequest) GetClientApi() uint32 {
	if x != nil {
		return x.ClientApi
	}
	return 0
}

type ExecuteHookPreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteHookPreResponse) Reset() {
	*x = ExecuteHookPreResponse{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteHookPreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteHookPreResponse) ProtoMessage() {}

func (x *ExecuteHookPreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteHookPreResponse.ProtoReflect.Descriptor instead.
func (*ExecuteHookPreResponse) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{5}
}

type ExecuteHookPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          *ExecutedHook          `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	ClientApi     uint32                 `protobuf:"varint,2,opt,name=client_api,json=clientApi,proto3" json:"client_api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteHookPostRequest) Reset() {
	*x = ExecuteHookPostRequest{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteHookPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteHookPostRequest) ProtoMessage() {}

func (x *ExecuteHookPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteHookPostRequest.ProtoReflect.Descriptor instead.
func (*ExecuteHookPostRequest) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteHookPostRequest) GetHook() *ExecutedHook {
	if x != nil {
		return x.Hook
	}
	return nil
}

func (x *ExecuteHookPostRequest) GetClientApi() uint32 {
	if x != nil {
		return x.ClientApi
	}
	return 0
}

type ExecuteHookPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteHookPostResponse) Reset() {
	*x = ExecuteHookPostResponse{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteHookPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteHookPostResponse) ProtoMessage() {}

func (x *ExecuteHookPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteHookPostResponse.ProtoReflect.Descriptor instead.
func (*ExecuteHookPostResponse) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{7}
}

type ExecuteHookCleanUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          *ExecutedHook          `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	ClientApi     uint32                 `protobuf:"varint,2,opt,name=client_api,json=clientApi,proto3" json:"client_api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteHookCleanUpRequest) Reset() {
	*x = ExecuteHookCleanUpRequest{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteHookCleanUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteHookCleanUpRequest) ProtoMessage() {}

func (x *ExecuteHookCleanUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteHookCleanUpRequest.ProtoReflect.Descriptor instead.
func (*ExecuteHookCleanUpRequest) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteHookCleanUpRequest) GetHook() *ExecutedHook {
	if x != nil {
		return x.Hook
	}
	return nil
}

func (x *ExecuteHookCleanUpRequest) GetClientApi() uint32 {
	if x != nil {
		return x.ClientApi
	}
	return 0
}

type ExecuteHookCleanUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteHookCleanUpResponse) Reset() {
	*x = ExecuteHookCleanUpResponse{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteHookCleanUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteHookCleanUpResponse) ProtoMessage() {}

func (x *ExecuteHookCleanUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteHookCleanUpResponse.ProtoReflect.Descriptor instead.
func (*ExecuteHookCleanUpResponse) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{9}
}

type GetChainInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainInfoRequest) Reset() {
	*x = GetChainInfoRequest{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainInfoRequest) ProtoMessage() {}

func (x *GetChainInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainInfoRequest.ProtoReflect.Descriptor instead.
func (*GetChainInfoRequest) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{10}
}

type GetChainInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainInfo     *ChainInfo             `protobuf:"bytes,1,opt,name=chain_info,json=chainInfo,proto3" json:"chain_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainInfoResponse) Reset() {
	*x = GetChainInfoResponse{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainInfoResponse) ProtoMessage() {}

func (x *GetChainInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainInfoResponse.ProtoReflect.Descriptor instead.
func (*GetChainInfoResponse) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetChainInfoResponse) GetChainInfo() *ChainInfo {
	if x != nil {
		return x.ChainInfo
	}
	return nil
}

type GetIgniteInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIgniteInfoRequest) Reset() {
	*x = GetIgniteInfoRequest{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIgniteInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIgniteInfoRequest) ProtoMessage() {}

func (x *GetIgniteInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIgniteInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIgniteInfoRequest) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{12}
}

type GetIgniteInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IgniteInfo    *IgniteInfo            `protobuf:"bytes,1,opt,name=ignite_info,json=igniteInfo,proto3" json:"ignite_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIgniteInfoResponse) Reset() {
	*x = GetIgniteInfoResponse{}
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIgniteInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIgniteInfoResponse) ProtoMessage() {}

func (x *GetIgniteInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ignite_services_plugin_grpc_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIgniteInfoResponse.ProtoReflect.Descriptor instead.
func (*GetIgniteInfoResponse) Descriptor() ([]byte, []int) {
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetIgniteInfoResponse) GetIgniteInfo() *IgniteInfo {
	if x != nil {
		return x.IgniteInfo
	}
	return nil
}

var File_ignite_services_plugin_grpc_v1_service_proto protoreflect.FileDescriptor

const file_ignite_services_plugin_grpc_v1_service_proto_rawDesc = "" +
	"\n" +
	",ignite/services/plugin/grpc/v1/service.proto\x12\x1eignite.services.plugin.grpc.v1\x1a/ignite/services/plugin/grpc/v1/client_api.proto\x1a.ignite/services/plugin/grpc/v1/interface.proto\"\x11\n" +
	"\x0fManifestRequest\"X\n" +
	"\x10ManifestResponse\x12D\n" +
	"\bmanifest\x18\x01 \x01(\v2(.ignite.services.plugin.grpc.v1.ManifestR\bmanifest\"r\n" +
	"\x0eExecuteRequest\x12A\n" +
	"\x03cmd\x18\x01 \x01(\v2/.ignite.services.plugin.grpc.v1.ExecutedCommandR\x03cmd\x12\x1d\n" +
	"\n" +
	"client_api\x18\x02 \x01(\rR\tclientApi\"\x11\n" +
	"\x0fExecuteResponse\"x\n" +
	"\x15ExecuteHookPreRequest\x12@\n" +
	"\x04hook\x18\x01 \x01(\v2,.ignite.services.plugin.grpc.v1.ExecutedHookR\x04hook\x12\x1d\n" +
	"\n" +
	"client_api\x18\x02 \x01(\rR\tclientApi\"\x18\n" +
	"\x16ExecuteHookPreResponse\"y\n" +
	"\x16ExecuteHookPostRequest\x12@\n" +
	"\x04hook\x18\x01 \x01(\v2,.ignite.services.plugin.grpc.v1.ExecutedHookR\x04hook\x12\x1d\n" +
	"\n" +
	"client_api\x18\x02 \x01(\rR\tclientApi\"\x19\n" +
	"\x17ExecuteHookPostResponse\"|\n" +
	"\x19ExecuteHookCleanUpRequest\x12@\n" +
	"\x04hook\x18\x01 \x01(\v2,.ignite.services.plugin.grpc.v1.ExecutedHookR\x04hook\x12\x1d\n" +
	"\n" +
	"client_api\x18\x02 \x01(\rR\tclientApi\"\x1c\n" +
	"\x1aExecuteHookCleanUpResponse\"\x15\n" +
	"\x13GetChainInfoRequest\"`\n" +
	"\x14GetChainInfoResponse\x12H\n" +
	"\n" +
	"chain_info\x18\x01 \x01(\v2).ignite.services.plugin.grpc.v1.ChainInfoR\tchainInfo\"\x16\n" +
	"\x14GetIgniteInfoRequest\"d\n" +
	"\x15GetIgniteInfoResponse\x12K\n" +
	"\vignite_info\x18\x01 \x01(\v2*.ignite.services.plugin.grpc.v1.IgniteInfoR\n" +
	"igniteInfo2\x81\x05\n" +
	"\x10InterfaceService\x12m\n" +
	"\bManifest\x12/.ignite.services.plugin.grpc.v1.ManifestRequest\x1a0.ignite.services.plugin.grpc.v1.ManifestResponse\x12j\n" +
	"\aExecute\x12..ignite.services.plugin.grpc.v1.ExecuteRequest\x1a/.ignite.services.plugin.grpc.v1.ExecuteResponse\x12\x7f\n" +
	"\x0eExecuteHookPre\x125.ignite.services.plugin.grpc.v1.ExecuteHookPreRequest\x1a6.ignite.services.plugin.grpc.v1.ExecuteHookPreResponse\x12\x82\x01\n" +
	"\x0fExecuteHookPost\x126.ignite.services.plugin.grpc.v1.ExecuteHookPostRequest\x1a7.ignite.services.plugin.grpc.v1.ExecuteHookPostResponse\x12\x8b\x01\n" +
	"\x12ExecuteHookCleanUp\x129.ignite.services.plugin.grpc.v1.ExecuteHookCleanUpRequest\x1a:.ignite.services.plugin.grpc.v1.ExecuteHookCleanUpResponse2\x8b\x02\n" +
	"\x10ClientAPIService\x12y\n" +
	"\fGetChainInfo\x123.ignite.services.plugin.grpc.v1.GetChainInfoRequest\x1a4.ignite.services.plugin.grpc.v1.GetChainInfoResponse\x12|\n" +
	"\rGetIgniteInfo\x124.ignite.services.plugin.grpc.v1.GetIgniteInfoRequest\x1a5.ignite.services.plugin.grpc.v1.GetIgniteInfoResponseB:Z8github.com/ignite/cli/v29/ignite/services/plugin/grpc/v1b\x06proto3"

var (
	file_ignite_services_plugin_grpc_v1_service_proto_rawDescOnce sync.Once
	file_ignite_services_plugin_grpc_v1_service_proto_rawDescData []byte
)

func file_ignite_services_plugin_grpc_v1_service_proto_rawDescGZIP() []byte {
	file_ignite_services_plugin_grpc_v1_service_proto_rawDescOnce.Do(func() {
		file_ignite_services_plugin_grpc_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ignite_services_plugin_grpc_v1_service_proto_rawDesc), len(file_ignite_services_plugin_grpc_v1_service_proto_rawDesc)))
	})
	return file_ignite_services_plugin_grpc_v1_service_proto_rawDescData
}

var file_ignite_services_plugin_grpc_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ignite_services_plugin_grpc_v1_service_proto_goTypes = []any{
	(*ManifestRequest)(nil),            // 0: ignite.services.plugin.grpc.v1.ManifestRequest
	(*ManifestResponse)(nil),           // 1: ignite.services.plugin.grpc.v1.ManifestResponse
	(*ExecuteRequest)(nil),             // 2: ignite.services.plugin.grpc.v1.ExecuteRequest
	(*ExecuteResponse)(nil),            // 3: ignite.services.plugin.grpc.v1.ExecuteResponse
	(*ExecuteHookPreRequest)(nil),      // 4: ignite.services.plugin.grpc.v1.ExecuteHookPreRequest
	(*ExecuteHookPreResponse)(nil),     // 5: ignite.services.plugin.grpc.v1.ExecuteHookPreResponse
	(*ExecuteHookPostRequest)(nil),     // 6: ignite.services.plugin.grpc.v1.ExecuteHookPostRequest
	(*ExecuteHookPostResponse)(nil),    // 7: ignite.services.plugin.grpc.v1.ExecuteHookPostResponse
	(*ExecuteHookCleanUpRequest)(nil),  // 8: ignite.services.plugin.grpc.v1.ExecuteHookCleanUpRequest
	(*ExecuteHookCleanUpResponse)(nil), // 9: ignite.services.plugin.grpc.v1.ExecuteHookCleanUpResponse
	(*GetChainInfoRequest)(nil),        // 10: ignite.services.plugin.grpc.v1.GetChainInfoRequest
	(*GetChainInfoResponse)(nil),       // 11: ignite.services.plugin.grpc.v1.GetChainInfoResponse
	(*GetIgniteInfoRequest)(nil),       // 12: ignite.services.plugin.grpc.v1.GetIgniteInfoRequest
	(*GetIgniteInfoResponse)(nil),      // 13: ignite.services.plugin.grpc.v1.GetIgniteInfoResponse
	(*Manifest)(nil),                   // 14: ignite.services.plugin.grpc.v1.Manifest
	(*ExecutedCommand)(nil),            // 15: ignite.services.plugin.grpc.v1.ExecutedCommand
	(*ExecutedHook)(nil),               // 16: ignite.services.plugin.grpc.v1.ExecutedHook
	(*ChainInfo)(nil),                  // 17: ignite.services.plugin.grpc.v1.ChainInfo
	(*IgniteInfo)(nil),                 // 18: ignite.services.plugin.grpc.v1.IgniteInfo
}
var file_ignite_services_plugin_grpc_v1_service_proto_depIdxs = []int32{
	14, // 0: ignite.services.plugin.grpc.v1.ManifestResponse.manifest:type_name -> ignite.services.plugin.grpc.v1.Manifest
	15, // 1: ignite.services.plugin.grpc.v1.ExecuteRequest.cmd:type_name -> ignite.services.plugin.grpc.v1.ExecutedCommand
	16, // 2: ignite.services.plugin.grpc.v1.ExecuteHookPreRequest.hook:type_name -> ignite.services.plugin.grpc.v1.ExecutedHook
	16, // 3: ignite.services.plugin.grpc.v1.ExecuteHookPostRequest.hook:type_name -> ignite.services.plugin.grpc.v1.ExecutedHook
	16, // 4: ignite.services.plugin.grpc.v1.ExecuteHookCleanUpRequest.hook:type_name -> ignite.services.plugin.grpc.v1.ExecutedHook
	17, // 5: ignite.services.plugin.grpc.v1.GetChainInfoResponse.chain_info:type_name -> ignite.services.plugin.grpc.v1.ChainInfo
	18, // 6: ignite.services.plugin.grpc.v1.GetIgniteInfoResponse.ignite_info:type_name -> ignite.services.plugin.grpc.v1.IgniteInfo
	0,  // 7: ignite.services.plugin.grpc.v1.InterfaceService.Manifest:input_type -> ignite.services.plugin.grpc.v1.ManifestRequest
	2,  // 8: ignite.services.plugin.grpc.v1.InterfaceService.Execute:input_type -> ignite.services.plugin.grpc.v1.ExecuteRequest
	4,  // 9: ignite.services.plugin.grpc.v1.InterfaceService.ExecuteHookPre:input_type -> ignite.services.plugin.grpc.v1.ExecuteHookPreRequest
	6,  // 10: ignite.services.plugin.grpc.v1.InterfaceService.ExecuteHookPost:input_type -> ignite.services.plugin.grpc.v1.ExecuteHookPostRequest
	8,  // 11: ignite.services.plugin.grpc.v1.InterfaceService.ExecuteHookCleanUp:input_type -> ignite.services.plugin.grpc.v1.ExecuteHookCleanUpRequest
	10, // 12: ignite.services.plugin.grpc.v1.ClientAPIService.GetChainInfo:input_type -> ignite.services.plugin.grpc.v1.GetChainInfoRequest
	12, // 13: ignite.services.plugin.grpc.v1.ClientAPIService.GetIgniteInfo:input_type -> ignite.services.plugin.grpc.v1.GetIgniteInfoRequest
	1,  // 14: ignite.services.plugin.grpc.v1.InterfaceService.Manifest:output_type -> ignite.services.plugin.grpc.v1.ManifestResponse
	3,  // 15: ignite.services.plugin.grpc.v1.InterfaceService.Execute:output_type -> ignite.services.plugin.grpc.v1.ExecuteResponse
	5,  // 16: ignite.services.plugin.grpc.v1.InterfaceService.ExecuteHookPre:output_type -> ignite.services.plugin.grpc.v1.ExecuteHookPreResponse
	7,  // 17: ignite.services.plugin.grpc.v1.InterfaceService.ExecuteHookPost:output_type -> ignite.services.plugin.grpc.v1.ExecuteHookPostResponse
	9,  // 18: ignite.services.plugin.grpc.v1.InterfaceService.ExecuteHookCleanUp:output_type -> ignite.services.plugin.grpc.v1.ExecuteHookCleanUpResponse
	11, // 19: ignite.services.plugin.grpc.v1.ClientAPIService.GetChainInfo:output_type -> ignite.services.plugin.grpc.v1.GetChainInfoResponse
	13, // 20: ignite.services.plugin.grpc.v1.ClientAPIService.GetIgniteInfo:output_type -> ignite.services.plugin.grpc.v1.GetIgniteInfoResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_ignite_services_plugin_grpc_v1_service_proto_init() }
func file_ignite_services_plugin_grpc_v1_service_proto_init() {
	if File_ignite_services_plugin_grpc_v1_service_proto != nil {
		return
	}
	file_ignite_services_plugin_grpc_v1_client_api_proto_init()
	file_ignite_services_plugin_grpc_v1_interface_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ignite_services_plugin_grpc_v1_service_proto_rawDesc), len(file_ignite_services_plugin_grpc_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ignite_services_plugin_grpc_v1_service_proto_goTypes,
		DependencyIndexes: file_ignite_services_plugin_grpc_v1_service_proto_depIdxs,
		MessageInfos:      file_ignite_services_plugin_grpc_v1_service_proto_msgTypes,
	}.Build()
	File_ignite_services_plugin_grpc_v1_service_proto = out.File
	file_ignite_services_plugin_grpc_v1_service_proto_goTypes = nil
	file_ignite_services_plugin_grpc_v1_service_proto_depIdxs = nil
}
