// Code generated by cmd/gen; DO NOT EDIT.
// Regenerate with: go run ./cmd/gen -in verifying_key.bin -out constants.go

package cometbls

import (
	bn254 "github.com/consensys/gnark-crypto/ecc/bn254"
)

// NbPublicInputs is the number of public inputs to the circuit, excluding the
// constant term and the Pedersen commitment contribution.
const NbPublicInputs = 2

// Pre-negated Groth16 verifying-key constants extracted from verifying_key.bin.
// BetaNegG2, GammaNegG2, DeltaNegG2 and PedersenGRootSigmaNeg are stored
// pre-negated so pairing checks can be evaluated as a single product equal to 1
// (matching the Rust cometbls-groth16-verifier).
var (
	AlphaG1               bn254.G1Affine
	BetaNegG2             bn254.G2Affine
	GammaNegG2            bn254.G2Affine
	DeltaNegG2            bn254.G2Affine
	PedersenG             bn254.G2Affine
	PedersenGRootSigmaNeg bn254.G2Affine
	GammaAbcG1            [3]bn254.G1Affine
)

func init() {
	mustG1(&AlphaG1, "245229d9b076b3c0e8a4d70bde8c1cccffa08a9fae7557b165b3b0dbd653e2c7253ec85988dbb84e46e94b5efa3373b47a000b4ac6c86b2d4b798d274a182302")
	mustG2(&BetaNegG2, "07090a82e8fabbd39299be24705b92cf208ee8b3487f6f2b39ff27978a29a1db2424bcc1f60a5472685fd50705b2809626e170120acaf441e133a2bd5e61d24425833b15e156ae01f2741f4f4120ddb466c52eb83a959f79eb99b23caa7fbf1d04ddc8d30d5c438ca34091c5d2c6ded571382cba2b3c4fdc4222df2938b4e51e")
	mustG2(&GammaNegG2, "198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c21800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed275dc4a288d1afb3cbb1ac09187524c7db36395df7be3b99e673b13a075a65ec1d9befcd05a5323e6da4d435f3b617cdb3af83285c2df711ef39c01571827f9d")
	mustG2(&DeltaNegG2, "07b8dbefa90bde075a26318e5066db729155514e3c06b888d4e03c56d82c97e602aca5d2a73f8d34e4b26eee3932365e6526c8d5e2f3347d679c2cb1867104dc2edb19cbb2b6ad0c98fdd7d1845500c26e497dc35e4cdc1cb02cc65dc4ba1bf21696ccafaefe49a5d8bad8e79630e19b25e5392a203aff0042d0216f254806f5")
	mustG2(&PedersenG, "198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c21800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa")
	mustG2(&PedersenGRootSigmaNeg, "07b8dbefa90bde075a26318e5066db729155514e3c06b888d4e03c56d82c97e602aca5d2a73f8d34e4b26eee3932365e6526c8d5e2f3347d679c2cb1867104dc2edb19cbb2b6ad0c98fdd7d1845500c26e497dc35e4cdc1cb02cc65dc4ba1bf21696ccafaefe49a5d8bad8e79630e19b25e5392a203aff0042d0216f254806f5")
	mustG1(&GammaAbcG1[0], "2f5d8a3817f21d3e453573c90c3cc47b7ff235fad7bdfbd59bbd6ae5d153273e147fa22142b1fd86ce75fc87230a0feac8765d02938784dcfc828d17d7e7c432")
	mustG1(&GammaAbcG1[1], "2a81b98e1c997bd01a20893a08a46c6804493e838c1a0ff6c8c069ef5ab66b9a276938ada8075cec20d4d6a1f157ec94cc7ba6207c98576e98c1ad9d6378fb6f")
	mustG1(&GammaAbcG1[2], "179496ce140df89ce35c5ee7fb496efdffda5e5d3b95ff9116e2e5df96b36ab70326e7d44688ce5903676b7d646e46a5938c8e5fd8cd54e4d5aa3300649f3cfc")
}

func mustG1(p *bn254.G1Affine, h string) {
	raw, err := decodeHex(h)
	if err != nil {
		panic("cometblsverifier: invalid G1 hex: " + err.Error())
	}
	if _, err := p.SetBytes(raw); err != nil {
		panic("cometblsverifier: invalid G1 point: " + err.Error())
	}
}

func mustG2(p *bn254.G2Affine, h string) {
	raw, err := decodeHex(h)
	if err != nil {
		panic("cometblsverifier: invalid G2 hex: " + err.Error())
	}
	if _, err := p.SetBytes(raw); err != nil {
		panic("cometblsverifier: invalid G2 point: " + err.Error())
	}
}

func decodeHex(s string) ([]byte, error) {
	out := make([]byte, len(s)/2)
	for i := 0; i < len(out); i++ {
		var b byte
		for j := 0; j < 2; j++ {
			c := s[2*i+j]
			switch {
			case c >= '0' && c <= '9':
				b = b<<4 | (c - '0')
			case c >= 'a' && c <= 'f':
				b = b<<4 | (c - 'a' + 10)
			case c >= 'A' && c <= 'F':
				b = b<<4 | (c - 'A' + 10)
			default:
				return nil, errInvalidHex
			}
		}
		out[i] = b
	}
	return out, nil
}

type hexErr string

func (e hexErr) Error() string { return string(e) }

const errInvalidHex = hexErr("invalid hex digit")
