name: ignite
base: core22 # the base snap is the execution environment for this snap
version: "{{version}}"
summary: Build, launch, and maintain any crypto application with Ignite CLI # 79 char long summary
description: |
  Ignite CLI offers everything you need to build, test, and launch your blockchain with a decentralized worldwide community. Ignite CLI is built on top of Cosmos SDK, the world's most popular blockchain framework.
  Ignite CLI accelerates chain development by scaffolding everything you need so you can focus on business logic.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic

parts:
  ignite:
    plugin: go
    source: https://github.com/ignite/cli.git
    source-tag: v{{version}}
    source-subdir: ignite/cmd/ignite
    build-snaps:
      - go

apps:
  ignite:
    command: bin/ignite
