#!/usr/bin/env node

var mode = process.argv[2];
process.argv.splice(2, 1);

switch (mode) {
  case "ts-proto":
    require("./node_modules/ts-proto/protoc-gen-ts_proto");
    break;

  case "tsc":
    require("./node_modules/typescript/bin/tsc");
    break;

  case "sta":
    require("./node_modules/swagger-typescript-api/index");
    break;

  case "ibc-setup":
    require("./node_modules/@confio/relayer/build/binary/ibc-setup/index");
    break;

  case "ibc-relayer":
    require("./node_modules/@confio/relayer/build/binary/ibc-relayer/index");
    break;

  default:
    console.error("unknown cli command");
}
