#!/usr/bin/env node

var mode = process.argv[2];
process.argv.splice(2, 1);

main();

function main() {
  switch (mode) {
    case "ts-proto":        require("ts-proto/protoc-gen-ts_proto");                    return;
    case "sta":             require("swagger-typescript-api/index");                    return;
    case "swagger-combine": require("swagger-combine/bin/swagger-combine");             return;
    case "ibc-setup":       require("@confio/relayer/build/binary/ibc-setup/index");    return;
    case "ibc-relayer":     require("@confio/relayer/build/binary/ibc-relayer/index");  return;
    case "xrelayer":        require("./dist/relayer");                                  return;
  }

  console.error("unknown cli command");
}
