// Generated by Ignite ignite.com/cli
import { Registry } from '@cosmjs/proto-signing'
import { IgniteClient } from "./client";
import { MissingWalletError } from "./helpers";
import { IgntModule as IgnitePlanetMars, msgTypes as IgnitePlanetMarsMsgTypes } from './ignite.planet.mars'


const Client = IgniteClient.plugin([
    IgnitePlanetMars
]);

const registry = new Registry([
  ...IgnitePlanetMarsMsgTypes,
  
])

export {
    Client,
    registry,
    MissingWalletError
}
