// Generated by Ignite ignite.com/cli
import { Registry } from '@cosmjs/proto-signing'
import { IgniteClient } from "./client";



const Client = IgniteClient.plugin([
    
]);

const registry = new Registry([
  
])

export {
    Client,
    registry
}
