{
  "name": "ts-sdk",
  "version": "0.1.0",
  "description": "Autogenerated cosmos modules vuex store",
  "author": "Starport Codegen <hello@tendermint.com>",  
  "license": "Apache-2.0",
  "licenses": [
    {
      "type": "Apache-2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  ],
  "main": "index.ts",
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@cosmjs/launchpad": "0.27.0",
    "@cosmjs/proto-signing": "0.27.0",
    "@cosmjs/stargate": "0.27.0",
    "@vue/composition-api": "^1.4.9",
    "axios": "^0.25.0",
    "events": "^3.3.0",
    "pinia": "^2.0.11"
  },
  "peerDependencies": {
    "pinia": "^2.0.11"
  }
}
