package gno

import (
	"fmt"
	"strings"
)

// tsClientHeader is the fixed prelude of generated TypeScript clients.
const tsClientHeader = `// Code generated by ignite. DO NOT EDIT.
// Client for {{.PkgPath}} ({{.Kind}}).

export interface GnoSigner {
  // signAndBroadcast broadcasts a MsgCall for pkgPath/func/args and returns
  // the tx result JSON. Implementations typically use the gno-js-client
  // or gnokey.
  signAndBroadcast(pkgPath: string, funcName: string, args: string[]): Promise<any>;
}

export class {{.Name}}Client {
  constructor(
    private readonly rpcURL: string,
    private readonly signer?: GnoSigner,
  ) {}
`

// GenerateTSClient renders a TypeScript client for the IDL. Queries use the
// read-only vm/qeval_json endpoint; realm calls go through the injected
// signer.
func GenerateTSClient(idl *IDL) string {
	var b strings.Builder

	header := strings.ReplaceAll(tsClientHeader, "{{.PkgPath}}", idl.PkgPath)
	header = strings.ReplaceAll(header, "{{.Kind}}", idl.Kind)
	header = strings.ReplaceAll(header, "{{.Name}}", tsPascal(idl.Name))
	b.WriteString(header)

	for _, instr := range idl.Instructions {
		writeTSMethod(&b, idl, instr)
	}

	b.WriteString("}\n")
	return b.String()
}

// writeTSMethod renders one client method for an instruction.
func writeTSMethod(b *strings.Builder, idl *IDL, instr IDLInstruction) {
	var (
		params   []string
		argNames []string
	)
	for _, arg := range instr.Args {
		params = append(params, fmt.Sprintf("%s: %s", tsCamel(arg.Name), tsType(arg.Type)))
		argNames = append(argNames, tsJSON("String("+tsCamel(arg.Name)+")"))
	}

	methodName := tsCamel(instr.Name)
	if instr.Realm {
		fmt.Fprintf(b, `
  // %s is a realm method (mutates on-chain state).
  async %s(%s): Promise<any> {
    if (!this.signer) {
      throw new Error("a GnoSigner is required to call realm methods");
    }
    return this.signer.signAndBroadcast(%q, %q, [%s]);
  }
`, instr.Name, methodName, strings.Join(params, ", "), idl.PkgPath, instr.Name, strings.Join(argNames, ", "))
		return
	}

	fmt.Fprintf(b, `
  // %s is a read-only expression evaluated on-chain.
  async %s(%s): Promise<string> {
    const expr = %q + "(" + [%s].join(", ") + ")";
    return this.eval(expr);
  }
`, instr.Name, methodName, strings.Join(params, ", "),
		idl.PkgPath+"."+instr.Name, strings.Join(argNames, ", "))

	// async eval helper only once
	if !strings.Contains(b.String(), "private async eval(") {
		b.WriteString(`
  private async eval(expression: string): Promise<string> {
    const res = await fetch(this.rpcURL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        jsonrpc: "2.0",
        id: 1,
        method: "abci_query",
        params: { path: "/vm/qeval_json", data: expression, height: "0", prove: false },
      }),
    });
    const json = await res.json();
    if (json.error) {
      throw new Error(json.error.message || json.error.data);
    }
    return json.result?.response?.value ?? "";
  }
`)
	}
}

// tsType maps a gno type to a TypeScript type.
func tsType(gnoType string) string {
	switch gnoType {
	case "string":
		return "string"
	case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16",
		"uint32", "uint64", "float32", "float64", "byte", "rune":
		return "number"
	case "bool":
		return "boolean"
	default:
		if strings.HasPrefix(gnoType, "[]") {
			return tsType(gnoType[2:]) + "[]"
		}
		return "any"
	}
}

// tsPascal upper-camel-cases an identifier for generated class names.
func tsPascal(name string) string {
	if name == "" {
		return name
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

// tsCamel lower-camel-cases an identifier.
func tsCamel(name string) string {
	if name == "" {
		return name
	}
	return strings.ToLower(name[:1]) + name[1:]
}

// tsJSON renders a call to JSON.stringify, producing a quoted gno string
// literal for arg arrays and expressions.
func tsJSON(valExpr string) string {
	return `JSON.stringify(` + valExpr + `)`
}
