// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	plugin "github.com/tendermint/starport/starport/services/plugin"
)

// StarportPlugin is an autogenerated mock type for the StarportPlugin type
type StarportPlugin struct {
	mock.Mock
}

// Execute provides a mock function with given fields: name, args
func (_m *StarportPlugin) Execute(name string, args []string) error {
	ret := _m.Called(name, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(name, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields:
func (_m *StarportPlugin) List() []plugin.FuncSpec {
	ret := _m.Called()

	var r0 []plugin.FuncSpec
	if rf, ok := ret.Get(0).(func() []plugin.FuncSpec); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plugin.FuncSpec)
		}
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *StarportPlugin) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Usage provides a mock function with given fields: name
func (_m *StarportPlugin) Usage(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
