#!/bin/bash

# ensure GOPATH and GOPATH/bin set.
gopath=$(go env GOPATH)
if [[ $PATH != *$gopath/bin* ]]; then
    echo 'export PATH=$PATH:$gopath/bin' >> $HOME/.bashrc
    . $HOME/.bashrc
fi

# build the dependencies..
echo "building the ui..."
rm -rf starport/ui/dist
(cd starport/ui && \
    npm i >/dev/null && \
    npm run build >/dev/null)

echo packing the ui...
go get -u github.com/gobuffalo/packr/v2/packr2 >/dev/null
(cd ./starport/interface/cli/starport && \
    packr2)

# gen statik dev ui.
go get github.com/rakyll/statik
statik -src=starport/ui/dist -dest=starport/ui/dist-go -f

# build Starport.
echo installing starport...
go install -mod=readonly ./... 1>/dev/null

echo done!
