#!/bin/bash

# generates static Go files to embed node cli programs into Starport for linux and darwin.

set -e

cd ./scripts/data/gen-nodetime

npm i 
npm run build

tar -czvf nodetime-linux-amd64.tar.gz nodetime-linux
tar -czvf nodetime-darwin-amd64.tar.gz nodetime-macos

mv nodetime-linux-amd64.tar.gz ../../../starport/pkg/nodetime/ 
mv nodetime-darwin-amd64.tar.gz ../../../starport/pkg/nodetime/

rm nodetime-linux nodetime-macos
rm -rf dist/
