#!/usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
IGNITE_REPO="https://github.com/ignite/cli.git"
SCAFFOLD_CMDS=(
    "chain example --no-module --skip-git"
    "module example --params param1:string,param2:bool --yes"
    "list list1 field1:string field2:int --module example --yes"
)
DIFF_EXCLUDE=(
    ".git"
    "*.md"
    "go.sum"
)

# Cleans up temporary files and directories
clean_up() {
    test -d "$1" && rm -fr "$1"
}

# Checks out to the given version tag and builds the Ignite CLI
checkout_and_build_ignite() (
    local ignite_dir="$1" version="$2"

    cd "$ignite_dir"
    git checkout --quiet "$version" && make build > /dev/null || exit 1
)

# Runs list of scaffold commands with the given ignite cli
scaffold_chain() {
    local ignite_cmd="$1" scaffold_path="$2"

    for cmd in "${SCAFFOLD_CMDS[@]}"; do
        $ignite_cmd scaffold $cmd --path $scaffold_path > /dev/null || (echo "Failed at scaffolding $cmd"; exit 1)
    done
}

# Generates diff between two directories
generate_diff() {
    local first_path="$1" second_path="$2"

    exclude_flags=()
    for exclude in "${DIFF_EXCLUDE[@]}"; do exclude_flags+=(-x "$exclude"); done

    diff -bur "$first_path" "$second_path" "${exclude_flags[@]}"
}

main() {
    tmp_dir=$(mktemp -d)
    trap "clean_up $tmp_dir" SIGINT SIGTERM ERR EXIT

    git clone "$IGNITE_REPO" "$tmp_dir/ignite" --quiet

    # Gets the latest version and the previous version
    versions=$(git tag --list --sort=version:refname 'v*')
    new_version=$(echo "${versions}" | tail -n 1); mkdir -p "$tmp_dir/$new_version"
    previous_version=$(echo "${versions}" | tail -n 2 | head -n 1); mkdir -p "$tmp_dir/$previous_version"
    echo "Generating migration documentation: ${previous_version} -> ${new_version}"

    checkout_and_build_ignite "$tmp_dir/ignite" "$previous_version"
    scaffold_chain "$tmp_dir/ignite/dist/ignite" "$tmp_dir/$previous_version"

    checkout_and_build_ignite "$tmp_dir/ignite" "$new_version"
    scaffold_chain "$tmp_dir/ignite/dist/ignite" "$tmp_dir/$new_version"

    # Getting diff between the two chains
    generate_diff "$tmp_dir/$previous_version" "$tmp_dir/$new_version" > "$SCRIPT_DIR"/"$previous_version"-"$new_version".diff
}

main