#!/bin/bash

os=`uname -s`
arch=`uname -m`

protoc_version=3.12.1
protoc_rel="https://github.com/protocolbuffers/protobuf/releases"
protoc_zip="protoc-$protoc_version-${os,,}-${arch,,}.zip"

# install protoc if not present
if [[ -z `which protoc` && ! -z $BIN_PATH ]]; then
	echo "installing protoc..."
	curl -LOs $protoc_rel/download/v$protoc_version/$protoc_zip
	unzip $protoc_zip -d $HOME/local
	mv $HOME/local/bin/protoc $BIN_PATH/protoc
	rm $protoc_zip
	protoc --version
fi

# build Starport.
echo installing starport...
go install -mod=readonly ./... 1>/dev/null

echo done!
