#!/bin/bash

# replace package's version to release version at package.json.
sed -i "s/\"version\": \".*\"/\"version\": \"$RELEASE_VERSION\"/g" ./.npm/package.json

cp readme.md .npm/

# publish!
npm publish --access public ./.npm
