#!/bin/bash

make && \

rm -rf tmp && mkdir tmp && cd tmp

echo "=> Creating an app"
starport app github.com/tendermint/blog 1>/dev/null
cd blog

echo "=> Creating a type"
starport type post title body 1>/dev/null

echo "=> Startig a server"
starport serve 1>/dev/null &
pid=$!
sleep 20

echo "=> Creating a blog post"
blogcli tx blog create-post foo bar --from user1 -y
sleep 10

echo "=> Listing blog posts"
blogcli q blog list-post

echo "=> Shutting down the server"
kill -s SIGINT $pid