#!/bin/bash

mkdir build
make 1>/dev/null && \

rm -rf tmp && mkdir tmp && cd tmp

echo "=> Creating an app"
starport app github.com/tendermint/blog
cd blog
ls

echo "=> Creating a type"
starport type post title body

echo "=> Startig a server"
starport serve &
pid=$!
sleep 20

echo "=> Creating a blog post"
~/go/bin/blogcli tx blog create-post foo bar --from user1 -y
sleep 10

echo "=> Listing blog posts"
~/go/bin/blogcli q blog list-post

echo "=> Shutting down the server"
kill -s SIGINT $pid