{
  "name": "{{ .PackageNS }}-client-ts",
  "version": "0.0.1",
  "description": "Autogenerated Typescript Client",
  "author": "Ignite Codegen <hello@ignite.com>",
  "license": "Apache-2.0",
  "licenses": [
    {
      "type": "Apache-2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  ],
  "main": "lib/index.js",
  "publishConfig": {
    "access": "public"
  },
  "scripts": {
    "build": "NODE_OPTIONS='--max-old-space-size=16384' tsc"
  },
  "dependencies": {   
    "@cosmjs/proto-signing": "0.33.1",
    "@cosmjs/stargate": "0.33.1",
    "@keplr-wallet/types": "^0.12.234",
    "axios": "1.9.0",
    "buffer": "^6.0.3",
    "events": "^3.3.0"
  },
  "peerDependencies": {
    "@cosmjs/proto-signing": "0.33.1",
    "@cosmjs/stargate": "0.33.1"
  }, 
  "devDependencies": {
    "@bufbuild/protobuf": "^2.4.0",
    "@types/events": "^3.0.3",
    "qs": "^6.14.0",
    "type-fest": "^4.41.0",
    "typescript": "^5.8.3"
  }
}
