{
  "name": "{{ .PackageNS }}-client-ts",
  "version": "0.0.1",
  "description": "Autogenerated Typescript Client",
  "author": "Ignite Codegen <hello@ignite.com>",
  "license": "Apache-2.0",
  "licenses": [
    {
      "type": "Apache-2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  ],
  "main": "index.ts",
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@cosmjs/launchpad": "0.27.0",
    "@cosmjs/proto-signing": "0.27.0",
    "@cosmjs/stargate": "0.27.0",
    "@keplr-wallet/types": "^0.11.3", 
    "axios": "0.21.4",
    "buffer": "^6.0.3",
    "events": "^3.3.0"
  },
  "peerDependencies": {
    "@cosmjs/launchpad": "0.27.0",
    "@cosmjs/proto-signing": "0.27.0",
    "@cosmjs/stargate": "0.27.0"
  }, 
  "devDependencies": {
    "@types/events": "^3.0.0",
    "typescript": "^4.8.4"
  }
}
