{
  "name": "{{ .User }}-{{ .Repo }}-vue",
  "version": "0.1.0",
  "description": "Autogenerated Vue API",
  "author": "Starport Codegen <hello@tendermint.com>",  
  "license": "Apache-2.0",
  "licenses": [
    {
      "type": "Apache-2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  ],
  "main": "index.ts",
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@vue/composition-api": "^1.4.9",
    "ts-client": "^0.1.0",
    "pinia": "^2.0.11"
  },
  "peerDependencies": {
    "pinia": "^2.0.11"
  }
}
