all: build

build:
	@mkdir -p build/
    @go build -mod=readonly -o build/<%= BinaryNamePrefix %>d ./cmd/<%= BinaryNamePrefix %>d
    @git go build -mod=readonly -o build/<%= BinaryNamePrefix %>cli ./cmd/<%= BinaryNamePrefix %>cli
